#!/usr/bin/env bash

case $1 in
    userena )   echo -e "\033[1mRunning tests for userena.\033[0m"
                cmd="demo/manage.py test userena"
                ;;
    umessages ) echo -e "\033[1mRunning tests for umessages.\033[0m"
                cmd="demo/manage.py test umessages"
                ;;
    * )         echo -e "\033[1mRunning all tests.\033[0m"
                cmd="demo/manage.py test userena umessages"
esac

$cmd
